FROM node:latest

WORKDIR /app

RUN apt-get update && apt-get install -y git

RUN npm install -g @nestjs/cli

RUN nest new back --package-manager yarn

WORKDIR /app/back

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
