FROM node:latest

WORKDIR /app

RUN apt-get update && apt-get install -y git

RUN npm install -g create-next-app

RUN yes | npx create-next-app@latest front

WORKDIR /app/front

RUN npm install

ENV NEXT_PUBLIC_PORT=3001

EXPOSE 3001

CMD ["npm", "run", "dev", "--", "-p", "3001"]