version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - 3001:3001
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - 3000:3000
  database: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database 
    expose:
      - 5432
    ports:
      - 5432:5432

